### PR TITLE
Fix caret after format

### PR DESCRIPTION
**Pull request by JairoMartinezA**
Hi @Alexey-T 
Help me to validate the next small change, basically fix the next "issue":

### Current behavior
Before conversion:
screenshot_07

After conversion:
screenshot_08

### After fix
After conversion:
screenshot_01

### CODE REVIEW

**Comment by Alexey-T** [comment]
in patch, you calc x0, x1, maxx - but don't use them later...

**Comment by Alexey-T** [comment]
patch makes x0=x1, y0=y1, then set_caret(x0,y0,x1,y1) works, so caret is made with EMPTY sel.

**Review by Alexey-T — CHANGES_REQUESTED** [review]
patch makes x0=x1, y0=y1, then set_caret(x0,y0,x1,y1) works, so caret is made with EMPTY sel.

**Comment by JairoMartinezA** [comment]
Fixing...

**Comment by JairoMartinezA** [comment]
Hi @Alexey-T 

I proceeded with some changes, but I think its is not necessary because the second part of the code will be reached only when the user formats all the content and in that case the caret always will have the form `(x0, y0, -1, -1)`. But maybe I am missing something.

screenshot_01

**Comment by Alexey-T** [comment]
i don't get it - how your screenshot relates to your patch... (patch seems Ok)

**Comment by JairoMartinezA** [comment]
Ok no no problem, just tell me if you see something else wrong.

Thanks @Alexey-T

**Comment by JairoMartinezA** [comment]
Sorry @Alexey-T 
I am not an experienced user in GitHub (Not yet :) ), I miss this part in the conversation:
screenshot_02

I suppose in this link I could have seen your code suggestions, but I missed it, and with mi force-push I can't see anymore the changes. I will have more care in the future. (y)

**Comment by Alexey-T** [comment]
why not making very simple patch?
we had before (before your fix)

            ed.set_caret(x0, y0, x1, y1)

maybe change it to goto line start

            ed.set_caret(0, min(y0, y1))

?

**Comment by JairoMartinezA** [comment]
Sure!!! for me is ok, I was thinking in a "smart" logic because of you :) but for me is ok :)

In that case if the change involves just to modify one line, could you ignore this merge request and add the modification that you are suggesting? for me is not a problem, as you want. Thanks.

**Comment by Alexey-T** [comment]
ok, applied this fix, will update plugin in 10 min.

**Pull request closed without merging**
